apiVersion: apps/v1
kind: Deployment
metadata:
  name: model
  labels:
    app: model
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model
  template:
    metadata:
      labels:
        app: model
    spec:
      containers:
      - name: model
        image: dkagialis/modell:08
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/bash", "-c", "/etc/init.d/sshd start" ]
        ports:
        - containerPort: 22
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-model2
  labels:
    app: ace2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ace2
  template:
    metadata:
      labels:
        app: ace2
    spec:
      containers:
      - name: ace2
        image: dkagialis/model:0.1
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/sh", "-c", "/etc/init.d/sshd start" ]
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: ace
spec:
  ports:
  - port: 22
  selector:
    app: ace
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ace-model
  labels:
    app: ace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ace
  template:
    metadata:
      labels:
        app: ace
    spec:
      containers:
      - name: ace
        image: dkagialis/test:1
        lifecycle:
          postStart:
            exec:
              command: [ "/bin/sh", "-c", "/etc/init.d/sshd start" ]
        ports:
        - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.23
        name: mysql
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
